"""Core data structures for DeepResearchAgent."""

from .config import (
    DAGExecutionConfig,
    LLMConfig,
    RedBlueLoopExecutionConfig,
    RunStoreConfig,
    SearchConfig,
    load_dag_execution_config_from_env,
    load_llm_config_from_env,
    load_red_blue_loop_config_from_env,
    load_run_store_config_from_env,
    load_search_config_from_env,
)
from .llm_client import (
    BaseLLMClient,
    LLMClientError,
    LLMMessage,
    LLMResponse,
    MockLLMClient,
    OpenAICompatibleLLMClient,
    create_llm_client,
)
from .prompt_loader import load_prompt
from .schema import (
    BlueRevisionResult,
    Citation,
    EvidenceSpan,
    Finding,
    GroundedFinding,
    PageContent,
    RedReviewResult,
    ResearchPlan,
    ResearchQuestion,
    ResearchReport,
    ReviewIssue,
    SearchResult,
    WebSearchResult,
)

__all__ = [
    "BaseLLMClient",
    "BlueRevisionResult",
    "Citation",
    "DAGExecutionConfig",
    "EvidenceSpan",
    "Finding",
    "GroundedFinding",
    "LLMClientError",
    "LLMConfig",
    "LLMMessage",
    "LLMResponse",
    "MockLLMClient",
    "OpenAICompatibleLLMClient",
    "PageContent",
    "RedReviewResult",
    "RedBlueLoopExecutionConfig",
    "ResearchPlan",
    "ResearchQuestion",
    "ResearchReport",
    "ReviewIssue",
    "RunStoreConfig",
    "SearchResult",
    "SearchConfig",
    "WebSearchResult",
    "create_llm_client",
    "load_dag_execution_config_from_env",
    "load_llm_config_from_env",
    "load_red_blue_loop_config_from_env",
    "load_run_store_config_from_env",
    "load_search_config_from_env",
    "load_prompt",
]
